// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dphbfs/fast-resume-tailoring/internal/adapter/cli"
	"github.com/dphbfs/fast-resume-tailoring/internal/adapter/jev"
	"github.com/dphbfs/fast-resume-tailoring/internal/app"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/config"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/logging"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/metrics"
	"github.com/dphbfs/fast-resume-tailoring/tuning"
)

// Injectors from wire.go:

// initApp builds the score CLI with every dependency wired from the
// environment.
func initApp() (*cli.ScoreApp, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	configJev := configConfig.Jev
	recorder := metrics.NewRecorder()
	logger := logging.New()
	client, err := jev.New(configJev, recorder, logger)
	if err != nil {
		return nil, err
	}
	configTuning := configConfig.Tuning
	tuningTuning, err := tuning.Load(configTuning)
	if err != nil {
		return nil, err
	}
	holisticJudge := app.NewHolisticJudge(client, recorder, logger, tuningTuning)
	configRun := configConfig.Run
	scoreApp := cli.NewScoreApp(holisticJudge, recorder, logger, configRun, tuningTuning)
	return scoreApp, nil
}
