// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dphbfs/fast-resume-tailoring/internal/adapter/cli"
	"github.com/dphbfs/fast-resume-tailoring/internal/adapter/jev"
	"github.com/dphbfs/fast-resume-tailoring/internal/adapter/openai"
	"github.com/dphbfs/fast-resume-tailoring/internal/app"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/config"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/logging"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/metrics"
)

// Injectors from wire.go:

// initApp builds the CLI with every dependency wired from the environment.
func initApp() (*cli.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	configJev := configConfig.Jev
	recorder := metrics.NewRecorder()
	logger := logging.New()
	client, err := jev.New(configJev, recorder, logger)
	if err != nil {
		return nil, err
	}
	generative := configConfig.Generative
	openaiClient, err := openai.New(generative, recorder, logger)
	if err != nil {
		return nil, err
	}
	pipeline := configConfig.Pipeline
	extractor := app.New(client, openaiClient, recorder, logger, pipeline)
	configRun := configConfig.Run
	cliApp := cli.New(extractor, recorder, logger, configRun)
	return cliApp, nil
}
