// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dphbfs/fast-resume-tailoring/internal/adapter/cli"
	"github.com/dphbfs/fast-resume-tailoring/internal/adapter/jev"
	"github.com/dphbfs/fast-resume-tailoring/internal/adapter/openai"
	"github.com/dphbfs/fast-resume-tailoring/internal/app"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/config"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/logging"
	"github.com/dphbfs/fast-resume-tailoring/internal/platform/metrics"
	"github.com/dphbfs/fast-resume-tailoring/internal/port"
	"github.com/google/wire"
)

// Injectors from wire.go:

// initApp builds the CLI with every dependency wired from the environment.
func initApp() (*cli.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	configJev := configConfig.Jev
	recorder := metrics.NewRecorder()
	logger := logging.New()
	client, err := jev.New(configJev, recorder, logger)
	if err != nil {
		return nil, err
	}
	generative := configConfig.Generative
	openaiClient, err := openai.New(generative, recorder, logger)
	if err != nil {
		return nil, err
	}
	pipeline := configConfig.Pipeline
	extractor := app.New(client, openaiClient, recorder, logger, pipeline)
	cliApp := cli.New(extractor, recorder, logger)
	return cliApp, nil
}

// wire.go:

var platformSet = wire.NewSet(config.Load, wire.FieldsOf(new(config.Config), "Jev", "Generative", "Pipeline"), logging.New, metrics.NewRecorder, wire.Bind(new(port.Metrics), new(*metrics.Recorder)))

var adapterSet = wire.NewSet(jev.New, wire.Bind(new(port.AIClassifierClient), new(*jev.Client)), openai.New, wire.Bind(new(port.AIGenerativeClient), new(*openai.Client)), cli.New)

var appSet = wire.NewSet(app.New, wire.Bind(new(port.RequirementExtractor), new(*app.Extractor)))
