// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dphbfs/fast-resume-scoring/internal/adapter/cli"
	"github.com/dphbfs/fast-resume-scoring/internal/adapter/openai"
	"github.com/dphbfs/fast-resume-scoring/internal/app"
	"github.com/dphbfs/fast-resume-scoring/internal/platform/config"
	"github.com/dphbfs/fast-resume-scoring/internal/platform/logging"
	"github.com/dphbfs/fast-resume-scoring/internal/platform/metrics"
	"github.com/dphbfs/fast-resume-scoring/internal/wiring"
	"github.com/dphbfs/fast-resume-scoring/tuning"
)

// Injectors from wire.go:

// initApp builds the CLI with every dependency wired from the environment.
func initApp() (*cli.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	jev := configConfig.Jev
	recorder := metrics.NewRecorder()
	logger := logging.New()
	aiClassifierClient, err := wiring.NewClassifier(jev, recorder, logger)
	if err != nil {
		return nil, err
	}
	generative := configConfig.Generative
	client, err := openai.New(generative, recorder, logger)
	if err != nil {
		return nil, err
	}
	pipeline := configConfig.Pipeline
	configTuning := configConfig.Tuning
	tuningTuning, err := tuning.Load(configTuning)
	if err != nil {
		return nil, err
	}
	extractor := app.New(aiClassifierClient, client, recorder, logger, pipeline, tuningTuning)
	configRun := configConfig.Run
	cliApp := cli.New(extractor, recorder, logger, configRun)
	return cliApp, nil
}
